#! /bin/sh
# TOOD: find out why XDG_CONFIG_HOME isn't defined

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

XDG_CONFIG_HOME=$("$SHELL" -c 'printenv XDG_CONFIG_HOME')
cd "$XDG_CONFIG_HOME"/lemonbar

killall panel > /dev/null ; ./panel &
